
name: bcar2-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python  # Base dependency
  - make
  - zlib        # Runtime library
  - pthread-stubs
  # These will be installed conditionally by the script
  # - gxx=11.3.0  # Will be added for Linux/Windows
  # - gcc=11.3.0  # Will be added for Linux/Windows
  # - clang_osx-arm64  # Will be added for macOS ARM64
  # - clangxx_osx-arm64  # Will be added for macOS ARM64